USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PROJECT_WH;
USE DATABASE RETAIL_PROJECT_DB;
USE SCHEMA CURATED;


-- ============================================================
-- CREATE ICEBERG TABLES
-- ============================================================

CREATE OR REPLACE ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.SALES_CURATED
    EXTERNAL_VOLUME = 'RETAIL_ICEBERG_VOLUME'
    CATALOG = 'RETAIL_GLUE_CATALOG'
    CATALOG_TABLE_NAME = 'sales_curated';


CREATE OR REPLACE ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.CUSTOMERS_CURATED
    EXTERNAL_VOLUME = 'RETAIL_ICEBERG_VOLUME'
    CATALOG = 'RETAIL_GLUE_CATALOG'
    CATALOG_TABLE_NAME = 'customers';


CREATE OR REPLACE ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.ORDERS_CURATED
    EXTERNAL_VOLUME = 'RETAIL_ICEBERG_VOLUME'
    CATALOG = 'RETAIL_GLUE_CATALOG'
    CATALOG_TABLE_NAME = 'orders';


CREATE OR REPLACE ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.PRODUCTS_CURATED
    EXTERNAL_VOLUME = 'RETAIL_ICEBERG_VOLUME'
    CATALOG = 'RETAIL_GLUE_CATALOG'
    CATALOG_TABLE_NAME = 'products';


CREATE OR REPLACE ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.CATEGORY_SUMMARY
    EXTERNAL_VOLUME = 'RETAIL_ICEBERG_VOLUME'
    CATALOG = 'RETAIL_GLUE_CATALOG'
    CATALOG_TABLE_NAME = 'category_summary';


CREATE OR REPLACE ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.PAYMENT_SUMMARY
    EXTERNAL_VOLUME = 'RETAIL_ICEBERG_VOLUME'
    CATALOG = 'RETAIL_GLUE_CATALOG'
    CATALOG_TABLE_NAME = 'payment_summary';


CREATE OR REPLACE ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.MARGIN
    EXTERNAL_VOLUME = 'RETAIL_ICEBERG_VOLUME'
    CATALOG = 'RETAIL_GLUE_CATALOG'
    CATALOG_TABLE_NAME = 'margin';


-- ============================================================
-- VERIFY ICEBERG OBJECTS WERE CREATED
-- ============================================================

SHOW ICEBERG TABLES
IN SCHEMA RETAIL_PROJECT_DB.CURATED;

-- Refresh tables

ALTER ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.CUSTOMERS_CURATED REFRESH;

ALTER ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.PRODUCTS_CURATED REFRESH;

ALTER ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.ORDERS_CURATED REFRESH;

ALTER ICEBERG TABLE RETAIL_PROJECT_DB.CURATED.SALES_CURATED REFRESH;